version: '3'

services:
  database:
    image: mysql:latest
    restart: always
    env_file: ./mysql/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/initdb:/docker-entrypoint-initdb.d

  api:
    build: ./note-api
    env_file:
      - ./note-api/api.env
      - ./mysql/mysql.env
    ports:
      - 1323:1323
    restart: always
    command: go run /api/src/main.go
    depends_on:
      - database

  frontend:
    build: ./frontend
    env_file: ./frontend/frontend.env
    ports:
      - 8080:8080
    # command: http-server dist
